/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-React_Native_Project-3WTDq0IRsOW1A3pKk0bwhZVcNCARVlvK",
  "version": "2020-11-20"
}

export default ebconfig;